/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RRouteImport } from './routes/r'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WechatCallbackRouteImport } from './routes/wechat.callback'
import { Route as LoginPhoneRouteImport } from './routes/login.phone'
import { Route as OauthWechatStartRouteImport } from './routes/oauth.wechat.start'
import { Route as OauthPhoneStartRouteImport } from './routes/oauth.phone.start'
import { Route as ApiSmsVerifyRouteImport } from './routes/api.sms.verify'
import { Route as ApiSmsSendRouteImport } from './routes/api.sms.send'
import { Route as ApiPublicSmsVerifyRouteImport } from './routes/api.public.sms.verify'
import { Route as ApiPublicSmsStartRouteImport } from './routes/api.public.sms.start'
import { Route as ApiPublicSmsSendRouteImport } from './routes/api.public.sms.send'
import { Route as ApiPublicOauthExchangeRouteImport } from './routes/api.public.oauth.exchange'
import { Route as ApiPublicOauthWechatExchangeRouteImport } from './routes/api.public.oauth.wechat.exchange'

const RRoute = RRouteImport.update({
  id: '/r',
  path: '/r',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WechatCallbackRoute = WechatCallbackRouteImport.update({
  id: '/wechat/callback',
  path: '/wechat/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPhoneRoute = LoginPhoneRouteImport.update({
  id: '/login/phone',
  path: '/login/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthWechatStartRoute = OauthWechatStartRouteImport.update({
  id: '/oauth/wechat/start',
  path: '/oauth/wechat/start',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthPhoneStartRoute = OauthPhoneStartRouteImport.update({
  id: '/oauth/phone/start',
  path: '/oauth/phone/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsVerifyRoute = ApiSmsVerifyRouteImport.update({
  id: '/api/sms/verify',
  path: '/api/sms/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsSendRoute = ApiSmsSendRouteImport.update({
  id: '/api/sms/send',
  path: '/api/sms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsVerifyRoute = ApiPublicSmsVerifyRouteImport.update({
  id: '/api/public/sms/verify',
  path: '/api/public/sms/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsStartRoute = ApiPublicSmsStartRouteImport.update({
  id: '/api/public/sms/start',
  path: '/api/public/sms/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsSendRoute = ApiPublicSmsSendRouteImport.update({
  id: '/api/public/sms/send',
  path: '/api/public/sms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthExchangeRoute = ApiPublicOauthExchangeRouteImport.update({
  id: '/api/public/oauth/exchange',
  path: '/api/public/oauth/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthWechatExchangeRoute =
  ApiPublicOauthWechatExchangeRouteImport.update({
    id: '/api/public/oauth/wechat/exchange',
    path: '/api/public/oauth/wechat/exchange',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/r': typeof RRoute
  '/login/phone': typeof LoginPhoneRoute
  '/wechat/callback': typeof WechatCallbackRoute
  '/api/sms/send': typeof ApiSmsSendRoute
  '/api/sms/verify': typeof ApiSmsVerifyRoute
  '/oauth/phone/start': typeof OauthPhoneStartRoute
  '/oauth/wechat/start': typeof OauthWechatStartRoute
  '/api/public/oauth/exchange': typeof ApiPublicOauthExchangeRoute
  '/api/public/sms/send': typeof ApiPublicSmsSendRoute
  '/api/public/sms/start': typeof ApiPublicSmsStartRoute
  '/api/public/sms/verify': typeof ApiPublicSmsVerifyRoute
  '/api/public/oauth/wechat/exchange': typeof ApiPublicOauthWechatExchangeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/r': typeof RRoute
  '/login/phone': typeof LoginPhoneRoute
  '/wechat/callback': typeof WechatCallbackRoute
  '/api/sms/send': typeof ApiSmsSendRoute
  '/api/sms/verify': typeof ApiSmsVerifyRoute
  '/oauth/phone/start': typeof OauthPhoneStartRoute
  '/oauth/wechat/start': typeof OauthWechatStartRoute
  '/api/public/oauth/exchange': typeof ApiPublicOauthExchangeRoute
  '/api/public/sms/send': typeof ApiPublicSmsSendRoute
  '/api/public/sms/start': typeof ApiPublicSmsStartRoute
  '/api/public/sms/verify': typeof ApiPublicSmsVerifyRoute
  '/api/public/oauth/wechat/exchange': typeof ApiPublicOauthWechatExchangeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/r': typeof RRoute
  '/login/phone': typeof LoginPhoneRoute
  '/wechat/callback': typeof WechatCallbackRoute
  '/api/sms/send': typeof ApiSmsSendRoute
  '/api/sms/verify': typeof ApiSmsVerifyRoute
  '/oauth/phone/start': typeof OauthPhoneStartRoute
  '/oauth/wechat/start': typeof OauthWechatStartRoute
  '/api/public/oauth/exchange': typeof ApiPublicOauthExchangeRoute
  '/api/public/sms/send': typeof ApiPublicSmsSendRoute
  '/api/public/sms/start': typeof ApiPublicSmsStartRoute
  '/api/public/sms/verify': typeof ApiPublicSmsVerifyRoute
  '/api/public/oauth/wechat/exchange': typeof ApiPublicOauthWechatExchangeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/health'
    | '/healthz'
    | '/r'
    | '/login/phone'
    | '/wechat/callback'
    | '/api/sms/send'
    | '/api/sms/verify'
    | '/oauth/phone/start'
    | '/oauth/wechat/start'
    | '/api/public/oauth/exchange'
    | '/api/public/sms/send'
    | '/api/public/sms/start'
    | '/api/public/sms/verify'
    | '/api/public/oauth/wechat/exchange'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/health'
    | '/healthz'
    | '/r'
    | '/login/phone'
    | '/wechat/callback'
    | '/api/sms/send'
    | '/api/sms/verify'
    | '/oauth/phone/start'
    | '/oauth/wechat/start'
    | '/api/public/oauth/exchange'
    | '/api/public/sms/send'
    | '/api/public/sms/start'
    | '/api/public/sms/verify'
    | '/api/public/oauth/wechat/exchange'
  id:
    | '__root__'
    | '/'
    | '/error'
    | '/health'
    | '/healthz'
    | '/r'
    | '/login/phone'
    | '/wechat/callback'
    | '/api/sms/send'
    | '/api/sms/verify'
    | '/oauth/phone/start'
    | '/oauth/wechat/start'
    | '/api/public/oauth/exchange'
    | '/api/public/sms/send'
    | '/api/public/sms/start'
    | '/api/public/sms/verify'
    | '/api/public/oauth/wechat/exchange'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  HealthRoute: typeof HealthRoute
  HealthzRoute: typeof HealthzRoute
  RRoute: typeof RRoute
  LoginPhoneRoute: typeof LoginPhoneRoute
  WechatCallbackRoute: typeof WechatCallbackRoute
  ApiSmsSendRoute: typeof ApiSmsSendRoute
  ApiSmsVerifyRoute: typeof ApiSmsVerifyRoute
  OauthPhoneStartRoute: typeof OauthPhoneStartRoute
  OauthWechatStartRoute: typeof OauthWechatStartRoute
  ApiPublicOauthExchangeRoute: typeof ApiPublicOauthExchangeRoute
  ApiPublicSmsSendRoute: typeof ApiPublicSmsSendRoute
  ApiPublicSmsStartRoute: typeof ApiPublicSmsStartRoute
  ApiPublicSmsVerifyRoute: typeof ApiPublicSmsVerifyRoute
  ApiPublicOauthWechatExchangeRoute: typeof ApiPublicOauthWechatExchangeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/r': {
      id: '/r'
      path: '/r'
      fullPath: '/r'
      preLoaderRoute: typeof RRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wechat/callback': {
      id: '/wechat/callback'
      path: '/wechat/callback'
      fullPath: '/wechat/callback'
      preLoaderRoute: typeof WechatCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/phone': {
      id: '/login/phone'
      path: '/login/phone'
      fullPath: '/login/phone'
      preLoaderRoute: typeof LoginPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/wechat/start': {
      id: '/oauth/wechat/start'
      path: '/oauth/wechat/start'
      fullPath: '/oauth/wechat/start'
      preLoaderRoute: typeof OauthWechatStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/phone/start': {
      id: '/oauth/phone/start'
      path: '/oauth/phone/start'
      fullPath: '/oauth/phone/start'
      preLoaderRoute: typeof OauthPhoneStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms/verify': {
      id: '/api/sms/verify'
      path: '/api/sms/verify'
      fullPath: '/api/sms/verify'
      preLoaderRoute: typeof ApiSmsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms/send': {
      id: '/api/sms/send'
      path: '/api/sms/send'
      fullPath: '/api/sms/send'
      preLoaderRoute: typeof ApiSmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms/verify': {
      id: '/api/public/sms/verify'
      path: '/api/public/sms/verify'
      fullPath: '/api/public/sms/verify'
      preLoaderRoute: typeof ApiPublicSmsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms/start': {
      id: '/api/public/sms/start'
      path: '/api/public/sms/start'
      fullPath: '/api/public/sms/start'
      preLoaderRoute: typeof ApiPublicSmsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms/send': {
      id: '/api/public/sms/send'
      path: '/api/public/sms/send'
      fullPath: '/api/public/sms/send'
      preLoaderRoute: typeof ApiPublicSmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/exchange': {
      id: '/api/public/oauth/exchange'
      path: '/api/public/oauth/exchange'
      fullPath: '/api/public/oauth/exchange'
      preLoaderRoute: typeof ApiPublicOauthExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/wechat/exchange': {
      id: '/api/public/oauth/wechat/exchange'
      path: '/api/public/oauth/wechat/exchange'
      fullPath: '/api/public/oauth/wechat/exchange'
      preLoaderRoute: typeof ApiPublicOauthWechatExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  HealthRoute: HealthRoute,
  HealthzRoute: HealthzRoute,
  RRoute: RRoute,
  LoginPhoneRoute: LoginPhoneRoute,
  WechatCallbackRoute: WechatCallbackRoute,
  ApiSmsSendRoute: ApiSmsSendRoute,
  ApiSmsVerifyRoute: ApiSmsVerifyRoute,
  OauthPhoneStartRoute: OauthPhoneStartRoute,
  OauthWechatStartRoute: OauthWechatStartRoute,
  ApiPublicOauthExchangeRoute: ApiPublicOauthExchangeRoute,
  ApiPublicSmsSendRoute: ApiPublicSmsSendRoute,
  ApiPublicSmsStartRoute: ApiPublicSmsStartRoute,
  ApiPublicSmsVerifyRoute: ApiPublicSmsVerifyRoute,
  ApiPublicOauthWechatExchangeRoute: ApiPublicOauthWechatExchangeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
